import type {
  HostDaemonRpcCommand,
  HostDaemonRpcCommandType,
} from "./commands.js";

export type HostDaemonCommandQuiescePolicy = "allowed" | "execution-start";

export const hostDaemonCommandQuiescePolicyByType = {
  "connect-tunnel.ensure-identity": "allowed",
  "desktop.browser.acquire_control": "execution-start",
  "desktop.browser.capture_tab": "allowed",
  "desktop.browser.close_tab": "allowed",
  "desktop.browser.create_tab": "execution-start",
  "desktop.browser.import_cookies": "execution-start",
  "desktop.browser.list_import_sources": "allowed",
  "desktop.browser.list_instances": "allowed",
  "desktop.browser.list_tabs": "allowed",
  "desktop.browser.open_connection": "execution-start",
  "desktop.browser.release_control": "allowed",
  "desktop.browser.reveal_tab": "allowed",
  "environment.attach": "execution-start",
  "environment.attach.cancel": "allowed",
  "environment.hook.cancel": "allowed",
  "environment.hook.run": "execution-start",
  "host.browse_directory": "allowed",
  "host.delete_skill": "execution-start",
  "host.file_metadata": "allowed",
  "host.global_skills_status": "allowed",
  "host.inspect_git_source": "allowed",
  "host.install_global_skills": "execution-start",
  "host.list_branch_options": "allowed",
  "host.list_commands": "allowed",
  "host.list_files": "allowed",
  "host.list_paths": "allowed",
  "host.list_skills": "allowed",
  "host.mkdir": "execution-start",
  "host.move_path": "execution-start",
  "host.paths_exist": "allowed",
  "host.pick_folder": "allowed",
  "host.read_file": "allowed",
  "host.read_file_relative": "allowed",
  "host.remove_path": "execution-start",
  "host.write_file": "execution-start",
  "host.write_skill": "execution-start",
  "interactive.resolve": "execution-start",
  "plugin.host.call": "execution-start",
  "plugin.host.cancel": "allowed",
  "plugin.host.dispose": "allowed",
  "project.clone": "execution-start",
  "project.clone_default_path": "allowed",
  "project.inspect": "allowed",
  "provider.health": "allowed",
  "provider.installation.run": "execution-start",
  "provider.installation.status": "allowed",
  "provider.list_models": "allowed",
  "provider.usage": "allowed",
  "server_move.abort": "allowed",
  "server_move.activate": "allowed",
  "server_move.delete_old_copy": "allowed",
  "server_move.inspect": "allowed",
  "server_move.prepare": "allowed",
  "server_move.probe": "allowed",
  "thread.archive": "allowed",
  "thread.goal.clear": "allowed",
  "thread.plan.cancel": "allowed",
  "thread.rename": "allowed",
  "thread.rewind.discard": "execution-start",
  "thread.rewind.prepare": "execution-start",
  "thread.start": "execution-start",
  "thread.stop": "allowed",
  "thread.storage.delete": "allowed",
  "thread.unarchive": "allowed",
  "turn.submit": "execution-start",
  "work.quiesce": "allowed",
  "work.seal": "allowed",
  "work.unquiesce": "allowed",
  "workspace.commit": "execution-start",
  "workspace.diff": "allowed",
  "workspace.diffFiles": "allowed",
  "workspace.diffPatch": "allowed",
  "workspace.pull_request": "allowed",
  "workspace.pull_request_action": "execution-start",
  "workspace.status": "allowed",
} satisfies Record<HostDaemonRpcCommandType, HostDaemonCommandQuiescePolicy>;

export function hostDaemonQuiescePolicyForCommand(
  command: HostDaemonRpcCommand,
): HostDaemonCommandQuiescePolicy {
  return hostDaemonCommandQuiescePolicyByType[command.type];
}
